# Generated by Django 4.2.1 on 2023-06-28 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
