# Generated by Django 4.2.1 on 2023-08-30 12:01

import campaign.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myblog', '0038_remove_advertisement_user_remove_placeadvert_advert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=campaign.models.renameadfiles)),
                ('urllink', models.URLField(max_length=255, verbose_name='urllink')),
                ('status', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='credit')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='discount')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True)),
                ('advert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.advertisement')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myblog.blogpostcategories')),
            ],
        ),
    ]
