# Generated by Django 4.2.1 on 2023-08-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_placeadvert_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
