# Generated by Django 4.2.1 on 2023-08-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_alter_advertisement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='duration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
