# Generated by Django 4.2.1 on 2023-08-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_advertisement_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='adverts/%Y/%m/%d/'),
        ),
    ]
