# Generated by Django 4.2.1 on 2023-08-31 20:00

import campaign.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_alter_advertisement_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-creation_date']},
        ),
        migrations.RenameField(
            model_name='placeadvert',
            old_name='num',
            new_name='adslot',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=campaign.models.renameadfiles),
        ),
    ]
