# Generated by Django 4.2.1 on 2023-09-02 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0007_alter_advertisement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('creation_date', models.DateField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateField(db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
