# Generated by Django 4.2.1 on 2023-09-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_advertcredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeadvert',
            name='ordering',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
