# Generated by Django 4.2.1 on 2023-09-03 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_placeadvert_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={},
        ),
    ]
