# Generated by Django 4.2.1 on 2023-07-17 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=130, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=255, verbose_name='eventname')),
                ('slug', models.SlugField(blank=True, max_length=130, verbose_name='slug')),
                ('image', models.FileField(blank=True, null=True, upload_to='Events/%Y/%m/%d/')),
                ('startdate', models.DateField()),
                ('starttime', models.TimeField()),
                ('enddate', models.DateField()),
                ('endtime', models.TimeField()),
                ('details', models.TextField(blank=True, null=True)),
                ('eventtype', models.CharField(blank=True, choices=[('0', 'In Person'), ('1', 'Virtual')], max_length=1, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.categories')),
                ('users_like', models.ManyToManyField(blank=True, related_name='event_liked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
    ]
