# Generated by Django 4.2.1 on 2023-07-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_events_eventtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='eventtype',
            field=models.CharField(blank=True, choices=[('0', 'In Person'), ('1', 'Virtual')], max_length=1, null=True),
        ),
    ]
