# Generated by Django 4.2.1 on 2023-08-02 18:28

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_events_eventtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
