# Generated by Django 4.2.1 on 2023-08-05 18:11

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_events_latitude_events_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326),
        ),
    ]
