# Generated by Django 4.2.1 on 2023-08-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_events_latitude_alter_events_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='eventvenue',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='eventvenue'),
        ),
    ]
