# Generated by Django 4.2.1 on 2023-08-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_events_eventvenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='endtime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
