# Generated by Django 4.2.1 on 2023-05-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostcategories',
            name='moderatoremail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
