# Generated by Django 4.2.1 on 2023-05-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_blogpostcategories_adrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='urllink',
            field=models.URLField(max_length=255, verbose_name='urllink'),
        ),
    ]
