# Generated by Django 4.2.1 on 2023-05-16 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myblog', '0004_alter_advertisement_urllink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='advertiser',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
