# Generated by Django 4.2.1 on 2023-05-22 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_rename_expiration_date_advertisement_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostSubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=130, verbose_name='slug')),
                ('moderatoremail', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('sub_title', models.CharField(blank=True, max_length=355, verbose_name='sub_title')),
                ('adrate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='adrate')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='discount')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myblog.blogpostcategories')),
            ],
        ),
    ]
