# Generated by Django 4.2.1 on 2023-06-01 23:10

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myblog', '0010_alter_blogpost_thumbnails'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubBlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=130, verbose_name='slug')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='FileUploads/%Y/%m/%d/')),
                ('thumbnails', models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/%d/')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.blogpostsubcategories')),
                ('users_like', models.ManyToManyField(blank=True, related_name='sub_posts_liked', to=settings.AUTH_USER_MODEL)),
                ('viewers', models.ManyToManyField(editable=False, related_name='viewed_sub_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
