# Generated by Django 4.2.1 on 2023-06-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0014_alter_subcomment_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnails',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
