# Generated by Django 4.2.1 on 2023-06-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0015_alter_blogpost_thumbnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnails',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/%d/', verbose_name='thumbnails'),
        ),
    ]
