# Generated by Django 4.2.1 on 2023-06-09 19:31

from django.db import migrations, models
import myblog.models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0018_remove_blogpost_image_remove_subblogpost_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to=myblog.models.renamefile),
        ),
        migrations.AddField(
            model_name='comment',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to=myblog.models.renamefile),
        ),
        migrations.AddField(
            model_name='comment',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to=myblog.models.renamefile),
        ),
        migrations.AddField(
            model_name='comment',
            name='image4',
            field=models.FileField(blank=True, null=True, upload_to=myblog.models.renamefile),
        ),
        migrations.AlterField(
            model_name='subblogpost',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to='FileUploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='subblogpost',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='FileUploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='subblogpost',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to='FileUploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='subblogpost',
            name='image4',
            field=models.FileField(blank=True, null=True, upload_to='FileUploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='subblogpost',
            name='thumbnails',
            field=models.FileField(blank=True, null=True, upload_to='thumbnails/%Y/%m/%d/'),
        ),
    ]
