# Generated by Django 4.2.1 on 2023-06-10 06:26

from django.db import migrations, models
import myblog.models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0019_comment_image1_comment_image2_comment_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileuploads',
            name='post',
        ),
        migrations.AddField(
            model_name='subcomment',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to=myblog.models.renamefile),
        ),
        migrations.AddField(
            model_name='subcomment',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to=myblog.models.renamefile),
        ),
        migrations.AddField(
            model_name='subcomment',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to=myblog.models.renamefile),
        ),
        migrations.AddField(
            model_name='subcomment',
            name='image4',
            field=models.FileField(blank=True, null=True, upload_to=myblog.models.renamefile),
        ),
        migrations.AlterField(
            model_name='subblogpost',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to=myblog.models.renamefile),
        ),
        migrations.AlterField(
            model_name='subblogpost',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to=myblog.models.renamefile),
        ),
        migrations.AlterField(
            model_name='subblogpost',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to=myblog.models.renamefile),
        ),
        migrations.AlterField(
            model_name='subblogpost',
            name='image4',
            field=models.FileField(blank=True, null=True, upload_to=myblog.models.renamefile),
        ),
        migrations.AlterField(
            model_name='subblogpost',
            name='thumbnails',
            field=models.FileField(blank=True, null=True, upload_to=myblog.models.renamethumbnails),
        ),
        migrations.DeleteModel(
            name='CommentFileUploads',
        ),
        migrations.DeleteModel(
            name='FileUploads',
        ),
    ]
