# Generated by Django 4.2.1 on 2023-06-10 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0020_remove_fileuploads_post_subcomment_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subfileuploads',
            name='post',
        ),
        migrations.DeleteModel(
            name='SubCommentFileUploads',
        ),
        migrations.DeleteModel(
            name='SubFileUploads',
        ),
    ]
