# Generated by Django 4.2.1 on 2023-06-11 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0021_remove_subfileuploads_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcomment',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='subcomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='subcomment',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-dateTime']},
        ),
        migrations.AlterModelOptions(
            name='subblogpost',
            options={'ordering': ['-dateTime']},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='myblog.blogpost'),
        ),
        migrations.AddField(
            model_name='subblogpost',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='myblog.subblogpost'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='SubComment',
        ),
    ]
