# Generated by Django 4.2.1 on 2023-06-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0027_alter_subblogpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='value', max_length=255, verbose_name='title'),
        ),
    ]
