# Generated by Django 4.2.1 on 2023-06-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0029_alter_blogpost_title_alter_subblogpost_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paginating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_pages', models.IntegerField(default=0)),
            ],
        ),
    ]
