# Generated by Django 4.2.1 on 2023-07-08 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0030_paginating'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='credit')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='discount')),
            ],
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='category',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='created',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='end_date',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PlaceAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(db_index=True)),
                ('advert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myblog.advertisement')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myblog.blogpostcategories')),
            ],
        ),
    ]
