# Generated by Django 4.2.1 on 2023-08-30 00:49

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myblog', '0031_uniquecodes_remove_advertisement_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeadvert',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='placeadvert',
            name='start_date',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='end_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='start_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='placeadvert',
            name='category',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placeadvert',
            name='category',
            field=models.ManyToManyField(blank=True, to='myblog.blogpostcategories'),
        ),
    ]
