# Generated by Django 4.2.1 on 2023-08-30 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myblog.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myblog', '0033_remove_placeadvert_advert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(db_index=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=myblog.models.renameadfiles)),
                ('urllink', models.URLField(max_length=255, verbose_name='urllink')),
                ('status', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myblog.advertisement')),
                ('category', models.ManyToManyField(blank=True, to='myblog.blogpostcategories')),
            ],
        ),
    ]
