# Generated by Django 4.2.1 on 2023-08-30 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0037_alter_advertisement_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='placeadvert',
            name='advert',
        ),
        migrations.RemoveField(
            model_name='placeadvert',
            name='category',
        ),
        migrations.DeleteModel(
            name='UniqueCodes',
        ),
        migrations.DeleteModel(
            name='Advertisement',
        ),
        migrations.DeleteModel(
            name='PlaceAdvert',
        ),
    ]
