# Generated by Django 4.2.1 on 2023-09-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0038_remove_advertisement_user_remove_placeadvert_advert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostcategories',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('D', 'Discount'), ('P', 'Premium')], max_length=1, null=True),
        ),
    ]
